language: node_js
node_js:
  - 6
  - 8
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn lint
  - yarn coverage
after_success:
  - codecov
env:
  global:
    secure: ck8mhOth02hiCv8+/lbFzABMOp2XsaNq4CHWivb5Ft8fTk92Eu03hNgfZ8oY+OsignL+G8bdY5zrbTZ4hBP72mB2pnIYNWgqhUVyOHM5MaUQNMusuVlwUNb63Q9NTQ1UcKkiXXtjfqAuOvB90HkUA9IMYyk47NllD420WAJvbDotPzgoGzSFVDM9eMe9e74gFMIHyYYq+x6JrSw5tPr2GE0sqinEmUzHbP6yJaeFigBbVRbrcELmzWf29botuli67qoirKZh23+eviYo59XCKvBoGkSi5N/n5jIju8EPsVZTu6Z2RBeGQ0fmPc9uDQXPOdllyMt2kV771vcOZAT7FBYntfZhlxGOMR+WC3StibGgITr4Bpp4se42OLdv5uUG8xg5pSZeYCElzXOAlfrmlo9WlxNEv5a2AbHvIPxBaO1iadOMxK5Bsq2icyUC3MrI6rBc4vgf4mkL2/LiCTM1rt6/dENsssRnyRLfqH7Mi0/N5GJ2Q4K0V5JWFwJvi2va9SN3VRlsPQoZC8x1HTcC6fUIv/AHAfLgS0VvsxxjwKRmLppRNC9wa50/2Yes5jsKaKH3jiTXMOVZd2/20PriMA3etO7eWjBX+0PjCJTj6VaJyDeE5tshEucFaXhkF2IyWXssO93eOtfhUMopxA22Uk2MXd2BccdwrJ6QuVeuKA4=
